### ISSUE TITLE
画像の扱い方

### ISSUE THREAD

**Issue by tosh7** [ninonanoni2038/Ito#3]
画像はimgファイルに入れるのではなく、Assets.xcassetsのファイルで管理するのがいいかな。

**Comment by ninonanoni2038** [comment]
次Pushで反映される〜。
画像をAssets.xcassetsで管理したほうがいい理由知りたい！

**Comment by tosh7** [comment]
- 本来画像は、画面の解像度によって@1、@2、@3みたいに用意しないといけない時に、xcassetsだと、それを管理しやすい。
- もう一つは、画像一覧を容易に探索しやすい。ファイルが増えてくると画像を探すのが大変になる、けども、xcassetsなら、xcassetsにとんで、そこからサムネイルで探せる。
- 基本的に、スタンダードな方法はxcassetsって覚えとくといいよ

**Comment by tosh7** [comment]
https://ja.stackoverflow.com/questions/21807/%E7%94%BB%E5%83%8F%E3%82%92%E7%BD%AE%E3%81%8F%E3%83%87%E3%82%A3%E3%83%AC%E3%82%AF%E3%83%88%E3%83%AA%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

**Comment by ninonanoni2038** [comment]
完全理解！DONE！
