### ISSUE TITLE
PrimaryKeyの設定

### ISSUE THREAD

**Issue by tosh7** [ninonanoni2038/Ito#5]
- Realmを使用するときは、PrimaryKeyの項目を予め設定しておいた方が良い。
→これがないと、削除、変更がうまくできなくなる。
・欲を言えば、Realmは自身のクラス内で作成、追加、削除、更新のメソッドを持つのが綺麗。
メンターOBのはるふさんの記事がとてもわかりやすい[Realmの使い方](https://qiita.com/_ha1f/items/f6318e326434dbf83037)

**Comment by ninonanoni2038** [comment]
反映Done

**Comment by tosh7** [comment]
とてもよくなってる！
